version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: finance_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
      image: redis:7-alpine
      container_name: finance_redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5
  app:
    build: .
    container_name: finance_app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_SERVER: postgres   # имя сервиса, а не localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: finance_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: